version: 2

models:
  - name: fct_logistics_reliability
    columns:
      - name: callsign
        data_tests:
          - not_null
      - name: reliability_status
        data_tests:
          - accepted_values:
              values: ['On-Time', 'Delayed']